name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: publish
      run: |
        git fetch --all
        git checkout gh-pages
        git checkout master -- index.html
        git checkout master -- static
        git checkout master -- js
        git add index.html static/ js/
        git commit -m "Publish application update"
        git push --force-with-lease origin gh-pages

