name: Publish to gh-pages

on:
 push:
   branches: [ "master" ]

jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4

   - name: publish
     run: |
       git config --global user.email "action@github.com"
       git config --global user.name "publish action"
       git fetch --all
       git checkout gh-pages
       git checkout master -- index.html
       git checkout master -- static
       git checkout master -- js
       git add index.html static/ js/
       git diff --quiet && git diff --staged --quiet || (git commit -m "Publish application update" && git push --force-with-lease origin gh-pages)
